name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - '**/*.php'
      - '**/*.js'
      - '**/*.scss'
      - '**/*.css'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Node Setup
        uses: actions/setup-node@v4.0.2
        with:
          cache: 'npm'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: theme-build
          path: './'
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.4
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          port: ${{ secrets.FTP_PORT }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: './wp-content/themes/it-residence/'
